development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  database: jif-mosaic
  username: jif-mosaic
  adapter: postgresql
  encoding: unicode
  password: n0n0n0n0
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
